---
# ====== Application: Demo Projects ==========================
identification: 
  name: Demo Projects
  alias: DEMO-PROJECTS
  version: Release 1.0

row-search: 
  tokenize: true
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: true
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: false
  pass-ecid: Y

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Oracle APEX Accounts # 101819632048883431311

authorization: 
  authorization-scheme: Reader Rights # 101819930090992431523
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Disabled

session-state-protection: 
  enabled: true

security: 
  deep-linking: Disabled
  browser-cache: Disabled
  embed-in-frames: Deny
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: WKSP_HKAWPFLOWCODE

globalization: 
  primary-language: English (en)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: true

application-format-masks: 
  date: DS
  timestamp: DS
  timestamp-time-zone: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: Demo Projects

progressive-web-app: 
  enable: true
  installable: true
  display: Standalone
  screen-orientation: Any
  ios-status-bar-style: Default
  enable-push-notifications: true
  pwa-push-notifications-credentials: App 153126 Push Notifications Credentials # 101820320922695434681

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:1:&APP_SESSION.::&DEBUG.:::'
    page: 1 # Home

  login-url: 
    url: 'f?p=&APP_ID.:LOGIN:&APP_SESSION.::&DEBUG.:::'
    page: LOGIN

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - t-TreeNav--styleA
  - js-navCollapsed--hidden
  list-position: Side
  list: Navigation Menu # 101819632801494431312

navigation-bar: 
  implementation: List
  list: Navigation Bar # 101819924792695431517
  list-template: Navigation Bar
  template-options: 
  - '#DEFAULT#'

javascript: 
  include-jquery-migrate: false

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: false
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_NAME ==============================
  id: 1
  identification: 
    name: APP_NAME

  value: 
    static-value: Demo Projects

component-settings: 
- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 21782111639305568
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 15537094410105

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 45425136847309197
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 15537094440729

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 69068191831312459
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 15537094463897

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 101819628750890431309
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 15525763290188

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 101819629099335431309
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER:TODAY-BUTTON'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 15525763290198

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 101819629339605431309
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 15525763290217

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 101819629673348431310
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 15525763290227

- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 101819629977348431310
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 15525763290244

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 101819630246889431310
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH_CB

  subscription: 
    version-number: 15525763290263

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 101819630501098431310
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 15525763290280

- # ====== Component Setting: NATIVE_IR ========================
  id: 101819630805375431310
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 15525763290282

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 101819631178015431310
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 15525763290285

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 101819631405215431310
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 15525763290287

application-settings: 
- # ====== Application Setting: FEEDBACK_ATTACHMENTS_YN ========
  id: 101819930901428431524
  identification: 
    name: FEEDBACK_ATTACHMENTS_YN

  value: 
    value: Y
    required: false

  advanced: 
    valid-values: Y, N
    on-upgrade-keep-value: true

  subscription: 
    version-number: 15525763297766

  configuration: 
    build-option: 'Feature: Feedback' # 101819927414214431522

- # ====== Application Setting: ACCESS_CONTROL_SCOPE ===========
  id: 101819931273051431524
  identification: 
    name: ACCESS_CONTROL_SCOPE

  value: 
    value: ACL_ONLY
    required: false

  advanced: 
    valid-values: ACL_ONLY, ALL_USERS
    on-upgrade-keep-value: true

  subscription: 
    version-number: 15525763297766

  configuration: 
    build-option: 'Feature: Access Control' # 101819927254948431522

  comments: 
    comments: The default access level given to authenticated users who are not in the access control list

